/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.learningkafka.services.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Category extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6842450008196670906L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Category\",\"namespace\":\"com.learningkafka.services.avro\",\"fields\":[{\"name\":\"categoryName\",\"type\":\"string\"},{\"name\":\"createdBy\",\"type\":\"long\"},{\"name\":\"lastModifiedBy\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Category> ENCODER =
      new BinaryMessageEncoder<Category>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Category> DECODER =
      new BinaryMessageDecoder<Category>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Category> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Category> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Category> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Category>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Category to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Category from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Category instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Category fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence categoryName;
   private long createdBy;
   private long lastModifiedBy;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Category() {}

  /**
   * All-args constructor.
   * @param categoryName The new value for categoryName
   * @param createdBy The new value for createdBy
   * @param lastModifiedBy The new value for lastModifiedBy
   */
  public Category(java.lang.CharSequence categoryName, java.lang.Long createdBy, java.lang.Long lastModifiedBy) {
    this.categoryName = categoryName;
    this.createdBy = createdBy;
    this.lastModifiedBy = lastModifiedBy;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return categoryName;
    case 1: return createdBy;
    case 2: return lastModifiedBy;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: categoryName = (java.lang.CharSequence)value$; break;
    case 1: createdBy = (java.lang.Long)value$; break;
    case 2: lastModifiedBy = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'categoryName' field.
   * @return The value of the 'categoryName' field.
   */
  public java.lang.CharSequence getCategoryName() {
    return categoryName;
  }


  /**
   * Sets the value of the 'categoryName' field.
   * @param value the value to set.
   */
  public void setCategoryName(java.lang.CharSequence value) {
    this.categoryName = value;
  }

  /**
   * Gets the value of the 'createdBy' field.
   * @return The value of the 'createdBy' field.
   */
  public long getCreatedBy() {
    return createdBy;
  }


  /**
   * Sets the value of the 'createdBy' field.
   * @param value the value to set.
   */
  public void setCreatedBy(long value) {
    this.createdBy = value;
  }

  /**
   * Gets the value of the 'lastModifiedBy' field.
   * @return The value of the 'lastModifiedBy' field.
   */
  public long getLastModifiedBy() {
    return lastModifiedBy;
  }


  /**
   * Sets the value of the 'lastModifiedBy' field.
   * @param value the value to set.
   */
  public void setLastModifiedBy(long value) {
    this.lastModifiedBy = value;
  }

  /**
   * Creates a new Category RecordBuilder.
   * @return A new Category RecordBuilder
   */
  public static com.learningkafka.services.avro.Category.Builder newBuilder() {
    return new com.learningkafka.services.avro.Category.Builder();
  }

  /**
   * Creates a new Category RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Category RecordBuilder
   */
  public static com.learningkafka.services.avro.Category.Builder newBuilder(com.learningkafka.services.avro.Category.Builder other) {
    if (other == null) {
      return new com.learningkafka.services.avro.Category.Builder();
    } else {
      return new com.learningkafka.services.avro.Category.Builder(other);
    }
  }

  /**
   * Creates a new Category RecordBuilder by copying an existing Category instance.
   * @param other The existing instance to copy.
   * @return A new Category RecordBuilder
   */
  public static com.learningkafka.services.avro.Category.Builder newBuilder(com.learningkafka.services.avro.Category other) {
    if (other == null) {
      return new com.learningkafka.services.avro.Category.Builder();
    } else {
      return new com.learningkafka.services.avro.Category.Builder(other);
    }
  }

  /**
   * RecordBuilder for Category instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Category>
    implements org.apache.avro.data.RecordBuilder<Category> {

    private java.lang.CharSequence categoryName;
    private long createdBy;
    private long lastModifiedBy;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.learningkafka.services.avro.Category.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.categoryName)) {
        this.categoryName = data().deepCopy(fields()[0].schema(), other.categoryName);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.createdBy)) {
        this.createdBy = data().deepCopy(fields()[1].schema(), other.createdBy);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.lastModifiedBy)) {
        this.lastModifiedBy = data().deepCopy(fields()[2].schema(), other.lastModifiedBy);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Category instance
     * @param other The existing instance to copy.
     */
    private Builder(com.learningkafka.services.avro.Category other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.categoryName)) {
        this.categoryName = data().deepCopy(fields()[0].schema(), other.categoryName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.createdBy)) {
        this.createdBy = data().deepCopy(fields()[1].schema(), other.createdBy);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.lastModifiedBy)) {
        this.lastModifiedBy = data().deepCopy(fields()[2].schema(), other.lastModifiedBy);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'categoryName' field.
      * @return The value.
      */
    public java.lang.CharSequence getCategoryName() {
      return categoryName;
    }


    /**
      * Sets the value of the 'categoryName' field.
      * @param value The value of 'categoryName'.
      * @return This builder.
      */
    public com.learningkafka.services.avro.Category.Builder setCategoryName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.categoryName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'categoryName' field has been set.
      * @return True if the 'categoryName' field has been set, false otherwise.
      */
    public boolean hasCategoryName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'categoryName' field.
      * @return This builder.
      */
    public com.learningkafka.services.avro.Category.Builder clearCategoryName() {
      categoryName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdBy' field.
      * @return The value.
      */
    public long getCreatedBy() {
      return createdBy;
    }


    /**
      * Sets the value of the 'createdBy' field.
      * @param value The value of 'createdBy'.
      * @return This builder.
      */
    public com.learningkafka.services.avro.Category.Builder setCreatedBy(long value) {
      validate(fields()[1], value);
      this.createdBy = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'createdBy' field has been set.
      * @return True if the 'createdBy' field has been set, false otherwise.
      */
    public boolean hasCreatedBy() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'createdBy' field.
      * @return This builder.
      */
    public com.learningkafka.services.avro.Category.Builder clearCreatedBy() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastModifiedBy' field.
      * @return The value.
      */
    public long getLastModifiedBy() {
      return lastModifiedBy;
    }


    /**
      * Sets the value of the 'lastModifiedBy' field.
      * @param value The value of 'lastModifiedBy'.
      * @return This builder.
      */
    public com.learningkafka.services.avro.Category.Builder setLastModifiedBy(long value) {
      validate(fields()[2], value);
      this.lastModifiedBy = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'lastModifiedBy' field has been set.
      * @return True if the 'lastModifiedBy' field has been set, false otherwise.
      */
    public boolean hasLastModifiedBy() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'lastModifiedBy' field.
      * @return This builder.
      */
    public com.learningkafka.services.avro.Category.Builder clearLastModifiedBy() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Category build() {
      try {
        Category record = new Category();
        record.categoryName = fieldSetFlags()[0] ? this.categoryName : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.createdBy = fieldSetFlags()[1] ? this.createdBy : (java.lang.Long) defaultValue(fields()[1]);
        record.lastModifiedBy = fieldSetFlags()[2] ? this.lastModifiedBy : (java.lang.Long) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Category>
    WRITER$ = (org.apache.avro.io.DatumWriter<Category>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Category>
    READER$ = (org.apache.avro.io.DatumReader<Category>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.categoryName);

    out.writeLong(this.createdBy);

    out.writeLong(this.lastModifiedBy);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.categoryName = in.readString(this.categoryName instanceof Utf8 ? (Utf8)this.categoryName : null);

      this.createdBy = in.readLong();

      this.lastModifiedBy = in.readLong();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.categoryName = in.readString(this.categoryName instanceof Utf8 ? (Utf8)this.categoryName : null);
          break;

        case 1:
          this.createdBy = in.readLong();
          break;

        case 2:
          this.lastModifiedBy = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










